org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

mod.id=EWR
mod.name=Extended Weather Radius
mod.group=dev.vesper
mod.version=1.0.2

deps.fabric-loader=0.19.3
deps.fabric-loom=1.17-SNAPSHOT
deps.fabric-kotlin=1.13.10+kotlin.2.3.20
deps.moddev=2.0.141
deps.kotlinforforge=6.2.0

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=QlSwG6aX
publish.curseforge=1461093
#publish.additionalVersions=