org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

mod.id=EWR
mod.name=Extended Weather Radius
mod.group=dev.vesper
mod.version=1.0.1

deps.fabric-loader=0.18.4
deps.fabric-loom=1.15-SNAPSHOT
deps.fabric-kotlin=1.13.4+kotlin.2.2.0
deps.moddev=2.0.95
deps.kotlinforforge=5.9.0

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=QlSwG6aX
publish.curseforge=1461093
#publish.additionalVersions=