modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "weatherradiusextended"
displayName = "Weather Radius Extended"
version = "${version}"
displayURL = ""
logoFile = "assets/icon.png"
authors = "VesMaybeVesper"
description = '''Increases the allowed radius of weather particles'''

[[mixins]]
config = "weatherradiusextended.mixins.json"

[[dependencies.weatherradiusextended]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.weatherradiusextended]]
modId = "minecraft"
type = "required"
